JovemProgramadorMVC/Models/AlunoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JovemProgramadorMVC.Models
{
    public class AlunoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Contato { get; set; }
        public string Email { get; set; }
        public string Cep { get; set; }
    }
}

JovemProgramadorMVC/Models/EnderecoModel.cs
namespace JovemProgramadorMVC.Models
{
    public class EnderecoModel
    {
        public string logradouro { get; set; }

        public string bairro { get; set; }

        public string uf { get; set; }

        public string ddd { get; set; }
    }
}

JovemProgramadorMVC/Models/ErrorViewModel.cs
using System;

namespace JovemProgramadorMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JovemProgramadorMVC/Controllers/AlunosController.cs
using JovemProgramadorMVC.Data.Repositorio.Interface;
using JovemProgramadorMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace JovemProgramadorMVC.Controllers
{
    public class AlunosController : Controller
    {
        private readonly IAlunoRepositorio _alunoRepositorio;
        private readonly IConfiguration _configuration;

        public AlunosController(IAlunoRepositorio alunoRepositorio, IConfiguration configuration)
        {
            _alunoRepositorio = alunoRepositorio;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            try
            {
                var alunos = _alunoRepositorio.BuscarAlunos();
                return View(alunos);
            }
            catch (System.Exception)
            {
                TempData["ErroAlunos"] = "Não foi encontrar os alunos cadastrados.";
                return View();
            }
        }

        public IActionResult AdicionarAluno()
        {
            return View();
        }

        public IActionResult InserirAluno(AlunoModel alunos)
        {
            try
            {
                _alunoRepositorio.InserirAluno(alunos);
            
                TempData["MensagemSucesso"] = "Aluno adicionado com sucesso!";
            }
            catch (System.Exception)
            {
                TempData["MensagemErro"] = "Não foi possível adicionar o aluno.";
            }
            return RedirectToAction("Index");
        }

        public IActionResult AlterarAluno(AlunoModel aluno)
        {
            _alunoRepositorio.EditarAluno(aluno);
            return RedirectToAction("Index");
        }        
        
        public IActionResult EditarAluno(int id)
        {
            try
            {
                var aluno = _alunoRepositorio.BuscarId(id);

                TempData["SucessoEdicao"] = "Aluno editado com sucesso!";

                return View(aluno);
            }
            catch (System.Exception)
            {
                TempData["ErroEdicao"] = "Não foi possível editar os dados do aluno.";
                return View();
            }
        }

        public IActionResult ExcluirAluno(AlunoModel aluno)
        {
            try
            {
                _alunoRepositorio.ExcluirAluno(aluno);

                TempData["SucessoExclusao"] = "Aluno excluído com sucesso!";

                return RedirectToAction("Index");
            }
            catch (System.Exception)
            {
                TempData["ErroExclusao"] = "Não foi possível excluir o aluno.";
                return View();
            }
        }

        public async Task<IActionResult> BuscarEndereco(string cep)
        {
            try
            {
                cep = cep.Replace("-", "");

                EnderecoModel enderecoModel = new();

                using var client = new HttpClient();

                var result = await client.GetAsync(_configuration.GetSection("ApiCep")["BaseUrl"] + cep + "/json");

                if(result.IsSuccessStatusCode)
                {
                    enderecoModel = JsonSerializer.Deserialize<EnderecoModel>(
                        await result.Content.ReadAsStringAsync(), new JsonSerializerOptions() { });
                }

                return View("Endereco", enderecoModel);
            }
            catch (System.Exception)
            {
                TempData["ErroBuscaEndereco"] = "Não encontrar o endereço solicitado.";
                return View();
            }
        }
    }
}

JovemProgramadorMVC/Controllers/ConhecimentosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JovemProgramadorMVC.Controllers
{
    public class ConhecimentosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

JovemProgramadorMVC/Controllers/HomeController.cs
 using JovemProgramadorMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace JovemProgramadorMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JovemProgramadorMVC/Controllers/ProfessoresController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JovemProgramadorMVC.Controllers
{
    public class ProfessoresController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

JovemProgramadorMVC/Views/Alunos/AdicionarAluno.cshtml
@{
    ViewData["Title"] = "Adicionar aluno";
}

@model AlunoModel

    <form asp-controller="Alunos" asp-action="InserirAluno" method="post">

        <div class="text-left">
            <div>
                <h1>Adiciona Novo Aluno</h1>
            </div>

            <div class="mb-3">
                <div>
                    <label for="exampleFormControlInput1" class="form-label">Nome</label>
                    <input type="text" asp-for="Nome" class="form-control" id="exampleFormControlInput1" placeholder="Your name"><br>
                </div>
                <div>
                    <label for="exampleFormControlInput1" class="form-label">Idade</label>
                    <input type="text" asp-for="Idade" class="form-control" id="exampleFormControlInput1" placeholder="00"><br>
                </div>
                <div>
                    <label for="exampleFormControlInput1" class="form-label">Contato</label>
                    <input type="text" asp-for="Contato" class="form-control" id="exampleFormControlInput1" placeholder="(00) 00000-0000"><br>
                </div>
                <div>
                    <label for="exampleFormControlInput1" class="form-label">E-mail</label>
                    <input type="email" asp-for="Email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com"><br>
                </div>
                <div>
                    <label for="exampleFormControlInput1" class="form-label">CEP</label>
                    <input type="text" asp-for="Cep" class="form-control" id="exampleFormControlInput1" placeholder="00000-000">
                </div>
            </div>

            <div class="d-grid gap-2 d-md-block text-center">
                <button class="btn btn-primary" type="submit">Adicionar</button>
                <a class="btn btn-primary" type="button" asp-controller="Alunos" asp-action="Index">Voltar</a>
            </div>
        </div>
    </form>

JovemProgramadorMVC/Views/Alunos/EditarAluno.cshtml
@{
    ViewData["Title"] = "Editar aluno";
}

@model AlunoModel

<form asp-controller="Alunos" asp-action="AlterarAluno" method="post">
    <input type="hidden" asp-for="Id"/>

    <div class="text-left">
        <div>
            <h1>Editar Aluno</h1>
        </div>

        <div class="mb-3">
            <div>
                <label for="exampleFormControlInput1" class="form-label">Nome</label>
                <input type="text" asp-for="Nome" class="form-control" id="exampleFormControlInput1" placeholder="Your name"><br>
            </div>
            <div>
                <label for="exampleFormControlInput1" class="form-label">Idade</label>
                <input type="text" asp-for="Idade" class="form-control" id="exampleFormControlInput1" placeholder="00"><br>
            </div>
            <div>
                <label for="exampleFormControlInput1" class="form-label">Contato</label>
                <input type="text" asp-for="Contato" class="form-control" id="exampleFormControlInput1" placeholder="(00) 00000-0000"><br>
            </div>
            <div>
                <label for="exampleFormControlInput1" class="form-label">E-mail</label>
                <input type="email" asp-for="Email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com"><br>
            </div>
            <div>
                <label for="exampleFormControlInput1" class="form-label">CEP</label>
                <input type="text" asp-for="Cep" class="form-control" id="exampleFormControlInput1" placeholder="00000-000">
            </div>
        </div>

        <div class="d-grid gap-2 d-md-block text-center">
            <button class="btn btn-primary" type="submit">Alterar</button>
            <a class="btn btn-primary" type="button" asp-controller="Alunos" asp-action="Index">Voltar</a>
        </div>
    </div>
</form>

JovemProgramadorMVC/Views/Alunos/Endereco.cshtml
@{
    ViewData["Title"] = "Endereço";
}

@model EnderecoModel

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <p>Logradouro: @Html.DisplayFor(endereco => endereco.logradouro)</p>
                <p>Bairro: @Html.DisplayFor(endereco => endereco.bairro)</p>
                <p>UF: @Html.DisplayFor(endereco => endereco.uf)</p>
                <p>DDD: @Html.DisplayFor(endereco => endereco.ddd)</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" type="button" asp-controller="Alunos" asp-action="Index">Fechar</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
    $(document).ready(function () {
            $('#myModal').modal('show');
        });</script>
}

JovemProgramadorMVC/Views/Alunos/ExcluirAluno.cshtml
@{
    ViewData["Title"] = "Aluno excluido";
}

@model AlunoModel

    <div class="text-center">
        <div>
            <h1>Aluno excluido com sucesso!</h1>
        </div>

        <div class="d-grid gap-3 d-md-block text-center">
            <a class="btn btn-primary" asp-controller="Alunos" asp-action="Index">Voltar</a>
        </div>
    </div>

JovemProgramadorMVC/Views/Alunos/Index.cshtml
@{
    ViewData["Title"] = "Alunos";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success">
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["SucessoEdicao"] != null)
{
    <div class="alert alert-success">
        @TempData["SucessoEdicao"]
    </div>
}

@if (TempData["SucessoExclusao"] != null)
{
    <div class="alert alert-success">
        @TempData["SucessoExclusao"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger">
        @TempData["MensagemErro"]
    </div>
}

@if (TempData["ErroAlunos"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErroAlunos"]
    </div>
}

@if (TempData["ErroEdicao"] != null)
{
<div class="alert alert-danger">
    @TempData["ErroEdicao"]
</div>
}

@if (TempData["ErroExclusao"] != null)
{
<div class="alert alert-danger">
    @TempData["ErroExclusao"]
</div>
}

@if (TempData["ErroBuscaEndereco"] != null)
{
<div class="alert alert-danger">
    @TempData["ErroBuscaEndereco"]
</div>
}

@model List<AlunoModel>

<div class="text-left">
    <div>
        <h1>Dados dos Alunos</h1>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Idade</th>
                <th scope="col">Contato</th>
                <th scope="col">E-mail</th>
                <th scope="col">CEP</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null && Model.Any())
            {
                foreach (AlunoModel aluno in Model)
                {
                    <tr>
                        <td>@aluno.Nome</td>
                        <td>@aluno.Idade</td>
                        <td>@aluno.Contato</td>
                        <td>@aluno.Email</td>
                        <td>@aluno.Cep</td>
                        <td>
                            <a type="submit" class="btn btn-primary" role="button" asp-controller="Alunos" asp-action="BuscarEndereco" asp-route-cep="@aluno.Cep">Endereço</a>
                        </td>
                        <td>
                            <a type="submit" class="btn btn-primary" role="button" asp-controller="Alunos" asp-action="EditarAluno" asp-route-id="@aluno.Id">Editar</a>
                        </td>
                        <td>
                            <a type="submit" class="btn btn-primary" role="button" asp-controller="Alunos" asp-action="ExcluirAluno" asp-route-id="@aluno.Id">Excluir</a>
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
    <div class="d-md-flex justify-content-md-center">
        <a type="button" class="btn btn-primary" asp-controller="Alunos" asp-action="AdicionarAluno">Adicionar novo aluno</a>
    </div>
</div>

JovemProgramadorMVC/Views/Conhecimentos/Index.cshtml
@{
    ViewData["Title"] = "Conhecimentos";
}

JovemProgramadorMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-left">
    <div>
        <h1>Sobre o Programa</h1>

        <p>O JOVEM PROGRAMADOR é um PROGRAMA de capacitação tecnológica para formação de jovens, de 16 a 35 anos, para atuar em empresas do Estado de Santa Catarina, independentemente do local onde estejam instaladas.</p>

        <p>O curso permite que jovens possam se capacitar em Tecnologia da Informação através do parceiro de ensino, o Senac - Serviço Nacional de Aprendizagem Comercial - que dispõe de ampla experiência na área de formação e capacitação de profissionais e disponibilizará as instalações em aproximadamente 20 municipios de Santa Catarina,</p>

        <p>Os jovens terão infraestrutura técnica e terão aulas de forma hibrida, presencial e virtual.</p>

        <p><b>A empregabilidade</b> é o foco do PROGRAMA, que não mede esforços de gerar oportunidade aos alunos egressos do PROGRAMA nas empresas parceiras. O objetivo é proporcionar aos alunos uma possibilidade de demonstrar suas habilidades perante as empresas patrocinadoras.</p>

        <p>O PROGRAMA se destina a jovens:</p>

        <ul>
            <li >Com idade entre 16 e 35 anos;</li>
            <li>A partir do 1º ano do ensino médio;</li>
            <li>Que residam nas cidades beneficiadas pelo programa ou em cidades vizinhas.</li>
        </ul>

        <p><b>O PROGRAMA é de iniciativa</b> do Sindicato das Empresas de Informática, Processamentos de Dados e Tecnologia da Informação do Estado de Santa Catarina - <b>SEPROSC</b> e realização do <b>SENAC</b>.</p>

        <p>Para a edição de 2022 as cidades são:</p>

        <p><b>Blumenau, Brusque, Caçador, Chapecó, Concórdia, Criciúma, Florianópolis, Jaraguá do Sul, Joaçaba, Joinville, Lages, Palhoça, Pinhalzinho, Rio do Sul e São Bento, São Miguel do Oeste, Tubarão, Videira, Xanxerê.</b></p>
        
        <p>Saiba mais sobre o programa no <a href="https://www.jovemprogramador.com.br/">site oficial</a>.</p>
    </div>
</div>

JovemProgramadorMVC/Views/Professores/Index.cshtml
@{
    ViewData["Title"] = "Professores";
}

<div class="text-left">
    <div>
        <h1>Dados dos Professores</h1>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Unidade</th>
                <th scope="col">Disciplina</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Kátia</td>
                <td>Brusque</td>
                <td>Desenvolvimento de Sistemas</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Nivaldo</td>
                <td>Brusque</td>
                <td>Banco de Dados</td>
            </tr>
        </tbody>
    </table>
</div>

JovemProgramadorMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JovemProgramador</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Jovem Programador</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professores" asp-action="Index">Professores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conhecimentos" asp-action="Index">Conhecimentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 Jovem Programador | contato@jovemprogramador.com.br | (47) 9918-44928
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>